### ISSUE TITLE
跨链应用章节中，测试 lockAndSendNFT出现异常。

### ISSUE THREAD

**Issue by telanks** [smartcontractkit/Web3_tutorial_Chinese#15]
## 测试代码
![image](https://github.com/user-attachments/assets/0f8df316-8b35-4b58-84b4-2b94f1b38098)

## 报错信息
![image](https://github.com/user-attachments/assets/903629ec-52fc-4b7c-832d-7f72f257acf1)

**Comment by QingyangKong** [comment]
请写一下如何复现这个问题

**Comment by zhangloveyan** [comment]
我也遇到了，排查了半天，是 ccip 的指南样例文档的代码更新导致的。

## 解决办法：

NFTPoolLockAndRelease 合约的 _buildCCIPMessage 方法修改传参：

![image](https://github.com/user-attachments/assets/45172974-2a61-4519-844c-06fcc3a51b92)

## 分析问题：

跟据报错信息分析，可以看到是 MockRouter 的 126 行 reverted 了
找到该代码如下：

![3](https://github.com/user-attachments/assets/ee6f5bd0-93e0-43fd-9967-cf67eccf2221)

可以看到是传参有问题，查看参数是 CCIP EVMExtraArgsV1

![4](https://github.com/user-attachments/assets/e48b8aa1-0f7c-4586-8078-45c061e141ac)

找到该参数传入位置：

![image](https://github.com/user-attachments/assets/ea4cd7de-98e1-4729-bd07-dc371688aaf6)

对比 ccip 的指南样例文档和课上的代码，就清楚了

![2](https://github.com/user-attachments/assets/a67bf6e7-0c88-4962-9423-b552db08d596)

**Comment by telanks** [comment]
> 请写一下如何复现这个问题

楼下已解决

**Comment by lzhflzjx** [comment]
![8a45437f9fe21f76015b10cae23d61b](https://github.com/user-attachments/assets/0d06c6c7-f343-4afa-b060-617183eef8a0)
![ddd4826e013456334854d63cd022dbd](https://github.com/user-attachments/assets/cd074d8a-7d70-4c07-b470-416c637bdb12)
或者把node_modules文件这样修改，测试用例也可以通过了
