### ISSUE TITLE
寻求sepolia ETH

### ISSUE THREAD

**Issue by chazex** [smartcontractkit/Web3_tutorial_Chinese#3]
我的地址是0x88Ec0Bb84f2Eb0682b6d74501b92Ddd70Fa8f261。 
教程中给的方式，每天只能获取0.1个不够用。
感谢。

**Comment by QingyangKong** [comment]
给你打了3个 SepoliaETH，如果以后不够，可以尝试使用 Avalanche Fuji，测试币比较容易获得

**Comment by chazex** [comment]
感谢。
