### ISSUE TITLE
等待区块确认时，偶尔出现异常

### ISSUE THREAD

**Issue by pengqiang323** [smartcontractkit/Web3_tutorial_Chinese#4]
fundMe.deploymentTransaction().wait(5)  
等待区块确认时，偶尔出现以下异常：
A network request failed. This is an error from the block explorer, not Hardhat. Error: Connect Timeout Error

**Comment by QingyangKong** [comment]
这个问题一般是由于网络连接不稳定引起的，当你的设备和RPC接口连接断开的时候就会出现这个问题。从代码上目前没有什么解决办法。
